import { Institution, Author, Specialty, Video } from "./types";

export const institutions: Institution[] = [
  { id: "inst-1", name: "UCLA", slug: "ucla" },
  { id: "inst-2", name: "University of Utah", slug: "university-of-utah" },
  { id: "inst-3", name: "Oregon Health & Science University", slug: "ohsu" },
  { id: "inst-4", name: "Southern Illinois University", slug: "siu" },
  { id: "inst-5", name: "Kaiser Permanente", slug: "kaiser-permanente" },
  { id: "inst-6", name: "West Los Angeles VA", slug: "west-la-va" },
];

export const authors: Author[] = [
  {
    id: "auth-1",
    name: "Christopher Lee",
    slug: "christopherlee",
    bio: "Assistant Professor of Orthopaedic Trauma at UCLA. Co-founder of Caseclips.",
    photoUrl: "/images/authors/Christopher-Lee.jpg",
    institutionId: "inst-1",
  },
  {
    id: "auth-2",
    name: "Adil Esmail",
    slug: "esmail",
    bio: "Chief of orthopedics service at Kaiser Permanente, Panorama City",
    photoUrl: "/images/authors/deiigryj3e7zjfyov1cx.jpg",
    institutionId: "inst-5",
  },
  {
    id: "auth-3",
    name: "Anthony Scaduto",
    slug: "scaduto",
    bio: "President and CEO of Orthopaedic Institute for Children, Chief of Pediatric Orthopaedics at UCLA",
    photoUrl: "/images/authors/Dr_Scaduto_PROFILE_gray.png",
    institutionId: "inst-1",
  },
  {
    id: "auth-4",
    name: "Darrel Brodke",
    slug: "darrel",
    bio: "Professor and Chair of the Department of Orthopaedics, University of Utah",
    photoUrl: "/images/authors/u0035272-1.jpg",
    institutionId: "inst-2",
  },
  {
    id: "auth-5",
    name: "Adam Sassoon",
    slug: "sassoon",
    bio: "Associate Professor of Adult Reconstruction at UCLA",
    photoUrl: "/images/authors/Adam-Sassoon.jpg",
    institutionId: "inst-1",
  },
  {
    id: "auth-6",
    name: "David Rothberg",
    slug: "david",
    bio: "Associate Professor of Orthopaedic Trauma at the University of Utah",
    photoUrl: "/images/authors/rothberg-2.jpg",
    institutionId: "inst-2",
  },
  {
    id: "auth-7",
    name: "Edward Cheung",
    slug: "edward",
    bio: "Assistant Professor of Orthopaedic Sports Medicine at UCLA",
    photoUrl: "/images/authors/Edward-Cheung-1.jpg",
    institutionId: "inst-1",
  },
  {
    id: "auth-8",
    name: "Mauricio Silva",
    slug: "mauricio",
    bio: "Medical Director of Orthopaedic Institute for Children, Clinical Professor of Orthopaedic Surgery at UCLA",
    photoUrl: "/images/authors/Dr_Silva_PROFILE_circle_gray.png",
    institutionId: "inst-1",
  },
  {
    id: "auth-9",
    name: "Steven Zeitzew",
    slug: "zeitzew",
    bio: "Professor of Orthopaedic Surgery at West Los Angeles VA Medical Center",
    photoUrl: "/images/authors/Steven-Zeitzew.jpg",
    institutionId: "inst-6",
  },
  {
    id: "auth-10",
    name: "John Horberg",
    slug: "john",
    bio: "Associate Professor of Adult Reconstruction at Southern Illinois University",
    photoUrl: "/images/authors/John-Horberg-Crop-scaled-1.jpg",
    institutionId: "inst-4",
  },
  {
    id: "auth-11",
    name: "James Lieber",
    slug: "james",
    bio: "PGY-4 Orthopaedic Resident at Southern Illinois University",
    photoUrl: "/images/authors/JPEG-image.jpeg",
    institutionId: "inst-4",
  },
  {
    id: "auth-12",
    name: "Rachel Thompson",
    slug: "thompson",
    bio: "Assistant Professor of Pediatric Orthopedics and Residency Program Director at UCLA",
    photoUrl: "/images/authors/thompson-rachel-1760793822-1.jpg",
    institutionId: "inst-1",
  },
  {
    id: "auth-13",
    name: "D. Gordon Allan",
    slug: "allan",
    bio: "Residency Program Director and Joint Reconstruction Fellowship Director at Southern Illinois University",
    photoUrl: "/images/authors/Dr.-D.-Gordon-Allan.png",
    institutionId: "inst-4",
  },
  {
    id: "auth-14",
    name: "Dane Brodke",
    slug: "dane",
    bio: "Assistant Professor of Orthopaedic Trauma at Oregon Health & Science University. Co-founder of Caseclips.",
    photoUrl: "/images/authors/Brodke--Dane_24-1-1-1.jpg",
    institutionId: "inst-3",
  },
  {
    id: "auth-15",
    name: "David Chen",
    slug: "david-chen",
    bio: "Medical Student at Oregon Health & Science University",
    photoUrl: "/images/authors/DC-full-headshot.jpg",
    institutionId: "inst-3",
  },
  {
    id: "auth-16",
    name: "Omar Nazir",
    slug: "nazir",
    bio: "Associate Professor of Orthopaedics at Oregon Health & Science University",
    photoUrl: "/images/authors/Nazir.jpg",
    institutionId: "inst-3",
  },
  {
    id: "auth-17",
    name: "Adam Mirarchi",
    slug: "mirarchi",
    bio: "Associate Professor of Orthopaedics at Oregon Health & Science University",
    photoUrl: "/images/authors/Mirarchi.jpg",
    institutionId: "inst-3",
  },
];

export const specialties: Specialty[] = [
  { id: "spec-1", name: "Trauma UE", slug: "trauma-ue" },
  { id: "spec-2", name: "Trauma LE", slug: "trauma-le" },
  { id: "spec-3", name: "Spine", slug: "spine" },
  { id: "spec-4", name: "Joints", slug: "joints" },
  { id: "spec-5", name: "Sports", slug: "sports" },
  { id: "spec-6", name: "Pediatrics", slug: "pediatrics" },
  { id: "spec-7", name: "Hand", slug: "hand" },
  { id: "spec-8", name: "Oncology", slug: "oncology" },
];

export const videos: Video[] = [
  {
    id: "693e36152c94f10001c3c7d3",
    title: "Scaphoid Fracture Fixation",
    slug: "scaphoid-fracture-fixation",
    vimeoId: "1146277093",
    thumbnailUrl: "/images/cases/scaphoid-preop-1.jpg",
    preopImages: ["/images/cases/scaphoid-preop.jpg"],
    postopImages: ["/images/cases/scaphoid-postop.jpg"],
    authorIds: ["auth-15", "auth-16", "auth-17"],
    specialtyIds: ["spec-7", "spec-1"],
    publishedAt: "2025-12-14",
  },
  {
    id: "643cb5120e9cc5003da0f7a9",
    title: "Total Knee Arthroplasty (Cementless, Robotic-assisted)",
    slug: "total-knee-arthroplasty-rosa",
    vimeoId: "818221174",
    thumbnailUrl: "/images/cases/PA-Flex-2.jpg",
    preopImages: ["/images/cases/PA-Flex.jpg"],
    postopImages: ["/images/cases/Postop-AP.jpeg"],
    authorIds: ["auth-13", "auth-11"],
    specialtyIds: ["spec-4"],
    publishedAt: "2023-04-17",
  },
  {
    id: "642b822c88d503003d6d0a4b",
    title: "Intra-articular Distal Humerus ORIF",
    slug: "intra-articular-distal-humerus-orif",
    vimeoId: "814443453",
    thumbnailUrl: "/images/cases/intra-art-humerus-preop-1.jpg",
    preopImages: ["/images/cases/intra-art-humerus-preop.jpg"],
    postopImages: ["/images/cases/intra-art-humerus-postop.jpg"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-1"],
    publishedAt: "2023-04-04",
  },
  {
    id: "641cb9f2374d1c003d2086e9",
    title: "Intertrochanteric Fracture Short Nail",
    slug: "intertrochanteric-fracture-short-nail",
    vimeoId: "811070811",
    thumbnailUrl: "/images/cases/Screenshot-2023-03-23-at-2.43.34-PM.jpg",
    preopImages: ["/images/cases/2023-03-preop.jpg"],
    postopImages: ["/images/cases/postop-2.jpg"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-2"],
    publishedAt: "2023-03-23",
  },
  {
    id: "63e98a46879664003d2ccc5b",
    title: "Varus Derotational Osteotomy of Proximal Femur",
    slug: "varus-derotational-osteotomy-of-proximal-femur",
    vimeoId: "798226088",
    thumbnailUrl: "/images/cases/Screenshot-2023-02-12-at-4.47.23-PM-1.jpg",
    preopImages: ["/images/cases/Screenshot-2023-02-12-at-4.47.23-PM.jpg"],
    postopImages: ["/images/cases/VDRO-postop.jpg"],
    authorIds: ["auth-12"],
    specialtyIds: ["spec-6"],
    publishedAt: "2023-02-18",
  },
  {
    id: "63e6ec21879664003d2ccbe8",
    title: "ACL Reconstruction (BTB autograft)",
    slug: "acl-reconstruction-btb",
    vimeoId: "797875201",
    thumbnailUrl: "/images/cases/ACL-preop-1.jpg",
    preopImages: ["/images/cases/ACL-preop.jpg"],
    postopImages: ["/images/cases/ACL-postop.jpg"],
    authorIds: ["auth-7"],
    specialtyIds: ["spec-5"],
    publishedAt: "2023-02-11",
  },
  {
    id: "63aba82f4a306b003dee3990",
    title: "Reverse Shoulder Arthroplasty (patient-specific guide)",
    slug: "reverse-shoulder-arth",
    vimeoId: "784633963",
    thumbnailUrl: "/images/cases/Cheung-RSA--2--preop-1.jpg",
    preopImages: ["/images/cases/Cheung-RSA--2--preop.jpg"],
    postopImages: ["/images/cases/Cheung-RSA--2--postop.jpg"],
    authorIds: ["auth-7"],
    specialtyIds: ["spec-5"],
    publishedAt: "2022-12-28",
  },
  {
    id: "63980ba83b6a66003d6acb69",
    title: "Anatomic Total Shoulder Arthroplasty",
    slug: "anatomic-total-shoulder-arthroplasty",
    vimeoId: "780588236",
    thumbnailUrl: "/images/cases/aTSA-preop.jpg",
    preopImages: ["/images/cases/aTSA-preop-1.jpg"],
    postopImages: ["/images/cases/aTSA-postop.jpg"],
    authorIds: ["auth-7"],
    specialtyIds: ["spec-5"],
    publishedAt: "2022-12-13",
  },
  {
    id: "637311d6a41e91003d300b8d",
    title: "Below Knee Amputation",
    slug: "below-knee-amputation",
    vimeoId: "770978360",
    thumbnailUrl: "/images/cases/Screen-Shot-2022-11-14-at-8.15.06-PM.png",
    preopImages: [],
    postopImages: [],
    authorIds: ["auth-9"],
    specialtyIds: ["spec-2", "spec-8"],
    publishedAt: "2022-11-15",
  },
  {
    id: "631a40051793c8003d9b14bb",
    title: "Glenoid Reconstruction with Allograft",
    slug: "distal-tibia-allograft-glenoid-reconstruction",
    vimeoId: "747510513",
    thumbnailUrl: "/images/cases/allograft-preop-1.jpg",
    preopImages: ["/images/cases/allograft-preop.jpg"],
    postopImages: ["/images/cases/2022-09-postop.jpg"],
    authorIds: ["auth-7"],
    specialtyIds: ["spec-5", "spec-1"],
    publishedAt: "2022-09-08",
  },
  {
    id: "630fe3261e9cb3003dd44307",
    title: "Total Hip Arthroplasty (Anterior)",
    slug: "total-hip-replacement-anterior",
    vimeoId: "745004972",
    thumbnailUrl: "/images/cases/anterior-THA-prep-1.jpg",
    preopImages: ["/images/cases/anterior-THA-prep.jpg"],
    postopImages: ["/images/cases/anterior-THA-postop.jpg"],
    authorIds: ["auth-10", "auth-11"],
    specialtyIds: ["spec-4"],
    publishedAt: "2022-08-31",
  },
  {
    id: "62781220f6c2dc004d5f8a41",
    title: "Periprosthetic Femur Fracture ORIF, Stem Revision",
    slug: "periprosthetic-femur-fracture-orif",
    vimeoId: "707418588",
    thumbnailUrl: "/images/cases/2022-05-preop-1.jpg",
    preopImages: ["/images/cases/2022-05-preop.jpg"],
    postopImages: ["/images/cases/postop.jpg"],
    authorIds: ["auth-5"],
    specialtyIds: ["spec-4", "spec-2"],
    publishedAt: "2022-05-08",
  },
  {
    id: "625b4db56dbef5003d4715b4",
    title: "Anterior Column Acetabulum ORIF",
    slug: "anterior-column-acetabular-orif",
    vimeoId: "700100663",
    thumbnailUrl: "/images/cases/anterior-column-preop-1.jpg",
    preopImages: ["/images/cases/anterior-column-preop.jpg"],
    postopImages: ["/images/cases/anterior-column-postop.jpg"],
    authorIds: ["auth-6"],
    specialtyIds: ["spec-2"],
    publishedAt: "2022-04-17",
  },
  {
    id: "622f999855cccb003dbcc90d",
    title: "Above Knee Amputation",
    slug: "above-knee-amputation",
    vimeoId: "688100558",
    thumbnailUrl: "/images/cases/AKA-preop--1-.jpg",
    preopImages: [],
    postopImages: [],
    authorIds: ["auth-9"],
    specialtyIds: ["spec-2", "spec-8"],
    publishedAt: "2022-03-14",
  },
  {
    id: "620aef053bcbb5003b7a4485",
    title: "Segmental Humerus ORIF",
    slug: "segmental-humerus-orif",
    vimeoId: "675693812",
    thumbnailUrl: "/images/cases/Segmental-humerus-preop.jpeg",
    preopImages: ["/images/cases/Segmental-humerus-preop-1-1.jpeg"],
    postopImages: ["/images/cases/Segmental-humerus-postop-1.jpeg"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-1"],
    publishedAt: "2022-02-10",
  },
  {
    id: "620aef053bcbb5003b7a4484",
    title: "Distal Biceps Repair",
    slug: "distal-biceps-repair",
    vimeoId: "662830466",
    thumbnailUrl: "/images/cases/distal-biceps.jpg",
    preopImages: [],
    postopImages: [],
    authorIds: ["auth-7"],
    specialtyIds: ["spec-5"],
    publishedAt: "2022-01-06",
  },
  {
    id: "620aef053bcbb5003b7a4483",
    title: "Total Hip Arthroplasty (Posterior)",
    slug: "total-hip-arthroplasty",
    vimeoId: "656422204",
    thumbnailUrl: "/images/cases/THA-preop-1.jpg",
    preopImages: ["/images/cases/THA-preop.jpg"],
    postopImages: ["/images/cases/THA-postop.jpg"],
    authorIds: ["auth-5"],
    specialtyIds: ["spec-4"],
    publishedAt: "2021-12-14",
  },
  {
    id: "620aef053bcbb5003b7a4482",
    title: "Olecranon and Radial Head ORIF",
    slug: "olecranon-radial-head-orif",
    vimeoId: "655953150",
    thumbnailUrl: "/images/cases/olecranon-radial-preop-2.jpg",
    preopImages: ["/images/cases/olecranon-radial-preop-1.jpg"],
    postopImages: ["/images/cases/olecranon-radial-postop.jpg"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-1"],
    publishedAt: "2021-12-13",
  },
  {
    id: "620aef053bcbb5003b7a4481",
    title: "Pectoralis Major Repair",
    slug: "pectoralis-major-repair",
    vimeoId: "650057481",
    thumbnailUrl: "/images/cases/pecrepair-preop.jpg",
    preopImages: [],
    postopImages: [],
    authorIds: ["auth-7"],
    specialtyIds: ["spec-5"],
    publishedAt: "2021-11-25",
  },
  {
    id: "620aef053bcbb5003b7a4480",
    title: "Pelvic Ring Fixation",
    slug: "pelvic-ring-fixation",
    vimeoId: "631654628",
    thumbnailUrl: "/images/cases/2021-10-preop-1.jpg",
    preopImages: ["/images/cases/preop.jpg"],
    postopImages: ["/images/cases/postop-3.jpg"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-2"],
    publishedAt: "2021-10-14",
  },
  {
    id: "620aef053bcbb5003b7a447f",
    title: "Subtrochanteric Femur ORIF",
    slug: "subtrochanteric-femur-orif",
    vimeoId: "599171612",
    thumbnailUrl: "/images/cases/preop.jpeg",
    preopImages: ["/images/cases/preop-1.jpeg"],
    postopImages: ["/images/cases/postop.jpeg"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-2"],
    publishedAt: "2021-09-06",
  },
  {
    id: "620aef053bcbb5003b7a447e",
    title: "Latarjet Procedure",
    slug: "latarjet-procedure",
    vimeoId: "582735478",
    thumbnailUrl: "/images/cases/latarjet-preop-1.jpg",
    preopImages: ["/images/cases/latarjet-preop.jpg"],
    postopImages: ["/images/cases/latarjet-postop.jpg"],
    authorIds: ["auth-7"],
    specialtyIds: ["spec-5"],
    publishedAt: "2021-08-04",
  },
  {
    id: "620aef053bcbb5003b7a447d",
    title: "Patella ORIF",
    slug: "patella-orif",
    vimeoId: "581025835",
    thumbnailUrl: "/images/cases/patella-preop.jpg",
    preopImages: ["/images/cases/patella-preop-1.jpg"],
    postopImages: ["/images/cases/patella-postop.jpg"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-2"],
    publishedAt: "2021-07-30",
  },
  {
    id: "620aef053bcbb5003b7a447c",
    title: "Femoral Neck ORIF",
    slug: "femoral-neck-orif",
    vimeoId: "571939944",
    thumbnailUrl: "/images/cases/fem-neck-preop-1.jpg",
    preopImages: ["/images/cases/fem-neck-preop.jpg"],
    postopImages: ["/images/cases/fem-neck-postop.jpg"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-2"],
    publishedAt: "2021-07-07",
  },
  {
    id: "620aef053bcbb5003b7a447a",
    title: "C1-2 Fusion",
    slug: "c1-2-fusion",
    vimeoId: "557847635",
    thumbnailUrl: "/images/cases/posterior-cervical-prep-1.jpg",
    preopImages: [],
    postopImages: ["/images/cases/posterior-cervical-prep.jpg", "/images/cases/posterior-cervical-postop.jpg"],
    authorIds: ["auth-4"],
    specialtyIds: ["spec-3"],
    publishedAt: "2021-06-01",
  },
  {
    id: "620aef053bcbb5003b7a4479",
    title: "Patellofemoral Arthroplasty",
    slug: "patellofemoral-arthroplasty",
    vimeoId: "551301765",
    thumbnailUrl: "/images/cases/2021-05-pre-op--1--3.jpg",
    preopImages: ["/images/cases/2021-05-pre-op--1--2.jpg"],
    postopImages: ["/images/cases/post-op--4-.jpg"],
    authorIds: ["auth-5"],
    specialtyIds: ["spec-4"],
    publishedAt: "2021-05-17",
  },
  {
    id: "620aef053bcbb5003b7a4477",
    title: "Reverse Shoulder Arthroplasty",
    slug: "reverse-shoulder-arthroplasty",
    vimeoId: "537419414",
    thumbnailUrl: "/images/cases/RSA-preop.jpg",
    preopImages: ["/images/cases/RSA-preop-1.jpg"],
    postopImages: ["/images/cases/RSA-postop.jpg"],
    authorIds: ["auth-7"],
    specialtyIds: ["spec-5"],
    publishedAt: "2021-04-15",
  },
  {
    id: "620aef053bcbb5003b7a4476",
    title: "Cervical Disc Replacement",
    slug: "cervical-disc-replacement",
    vimeoId: "537359941",
    thumbnailUrl: "/images/cases/cerv-disc-replacement-preop.jpg",
    preopImages: ["/images/cases/cerv-disc-replacement-preop-1.jpg"],
    postopImages: ["/images/cases/cerv-disc-replacement-postop.jpg"],
    authorIds: ["auth-4"],
    specialtyIds: ["spec-3"],
    publishedAt: "2021-04-15",
  },
  {
    id: "620aef053bcbb5003b7a4475",
    title: "Proximal Humerus ORIF",
    slug: "proximal-humerus-orif",
    vimeoId: "527633994",
    thumbnailUrl: "/images/cases/prox-humerus---preop.jpg",
    preopImages: ["/images/cases/prox-humerus---preop-1.jpg"],
    postopImages: ["/images/cases/prox-humerus---postop.jpg"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-1"],
    publishedAt: "2021-03-23",
  },
  {
    id: "620aef053bcbb5003b7a4474",
    title: "Unicompartmental Knee Arthroplasty",
    slug: "unicompartmental-knee-arthroplasty",
    vimeoId: "523336748",
    thumbnailUrl: "/images/cases/UKA---preop-1.jpg",
    preopImages: ["/images/cases/UKA---preop.jpg"],
    postopImages: ["/images/cases/UKA---postop.jpg"],
    authorIds: ["auth-5"],
    specialtyIds: ["spec-4"],
    publishedAt: "2021-03-14",
  },
  {
    id: "620aef053bcbb5003b7a4473",
    title: "Clavicle ORIF",
    slug: "clavicle-orif",
    vimeoId: "517604179",
    thumbnailUrl: "/images/cases/clavicle-preop-1.jpg",
    preopImages: ["/images/cases/clavicle-preop.jpg"],
    postopImages: ["/images/cases/clavicle-postop.jpg"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-1"],
    publishedAt: "2021-02-27",
  },
  {
    id: "620aef053bcbb5003b7a4472",
    title: "Tibial Plateau ORIF",
    slug: "tibial-plateau-orif",
    vimeoId: "512693946",
    thumbnailUrl: "/images/cases/plateau-preop-6.jpg",
    preopImages: ["/images/cases/plateau-preop-7.jpg"],
    postopImages: ["/images/cases/plateau-postop-1.jpg"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-2"],
    publishedAt: "2021-02-16",
  },
  {
    id: "620aef053bcbb5003b7a4471",
    title: "Surgical Hip Dislocation",
    slug: "surgical-hip-dislocation",
    vimeoId: "507330225",
    thumbnailUrl: "/images/cases/SHD-pre-op-3.jpg",
    preopImages: ["/images/cases/SHD-pre-op-2.jpg"],
    postopImages: ["/images/cases/SHD-post-op--1-.jpg"],
    authorIds: ["auth-5"],
    specialtyIds: ["spec-4", "spec-8", "spec-5"],
    publishedAt: "2021-02-02",
  },
  {
    id: "620aef053bcbb5003b7a4470",
    title: "Posterior Sacroiliac Joint Fixation",
    slug: "posterior-si-fixation",
    vimeoId: "505518551",
    thumbnailUrl: "/images/cases/si-joint-preop--2-.jpg",
    preopImages: ["/images/cases/si-joint-preop--2--1.jpg"],
    postopImages: ["/images/cases/Rothberg-SI-post-op.jpg"],
    authorIds: ["auth-6"],
    specialtyIds: ["spec-2"],
    publishedAt: "2021-01-28",
  },
  {
    id: "620aef053bcbb5003b7a446f",
    title: "L5-S1 Microdiscectomy",
    slug: "l5-s1-microdiscectomy",
    vimeoId: "502023431",
    thumbnailUrl: "/images/cases/microdisc-1.jpg",
    preopImages: ["/images/cases/microdisc.jpg"],
    postopImages: [],
    authorIds: ["auth-4"],
    specialtyIds: ["spec-3"],
    publishedAt: "2021-01-19",
  },
  {
    id: "620aef053bcbb5003b7a446e",
    title: "Total Knee Arthroplasty",
    slug: "total-knee-arthroplasty",
    vimeoId: "493208236",
    thumbnailUrl: "/images/cases/pre-op--1--2.jpg",
    preopImages: ["/images/cases/pre-op--1--3.jpg"],
    postopImages: ["/images/cases/post-op--2--1.jpg"],
    authorIds: ["auth-5"],
    specialtyIds: ["spec-4"],
    publishedAt: "2020-12-21",
  },
  {
    id: "620aef053bcbb5003b7a446d",
    title: "Olecranon ORIF",
    slug: "olecranon-orif",
    vimeoId: "492327171",
    thumbnailUrl: "/images/cases/pre-op--1--1.jpg",
    preopImages: ["/images/cases/pre-op--1-.jpg"],
    postopImages: ["/images/cases/post-op--2-.jpg"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-1"],
    publishedAt: "2020-12-18",
  },
  {
    id: "620aef053bcbb5003b7a446c",
    title: "L3-4 TLIF",
    slug: "l3-4-tlif",
    vimeoId: "471373717",
    thumbnailUrl: "/images/cases/Pre-op.jpg",
    preopImages: ["/images/cases/Pre-op-1.jpg"],
    postopImages: ["/images/cases/Post-op-1.jpg"],
    authorIds: ["auth-4"],
    specialtyIds: ["spec-3"],
    publishedAt: "2020-10-23",
  },
  {
    id: "620aef053bcbb5003b7a446b",
    title: "L5-S1 Anterior lumbar interbody fusion",
    slug: "l5-s1-alif",
    vimeoId: "469143849",
    thumbnailUrl: "/images/cases/Preop-2.jpg",
    preopImages: ["/images/cases/Preop-1.jpg"],
    postopImages: ["/images/cases/Post-op.jpg"],
    authorIds: ["auth-4"],
    specialtyIds: ["spec-3"],
    publishedAt: "2020-10-16",
  },
  {
    id: "620aef053bcbb5003b7a446a",
    title: "Radius/ulna shaft (both bone forearm) ORIF",
    slug: "both-bone-forearm-orif",
    vimeoId: "461594636",
    thumbnailUrl: "/images/cases/Both-bone-1.jpg",
    preopImages: ["/images/cases/Both-bone.jpg"],
    postopImages: ["/images/cases/Both-bone-post.jpg"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-1"],
    publishedAt: "2020-09-24",
  },
  {
    id: "620aef053bcbb5003b7a4468",
    title: "Supracondylar humerus CRPP",
    slug: "supracondylar-humerus-fracture-crpp",
    vimeoId: "455110112",
    thumbnailUrl: "/images/cases/SCHF.jpg",
    preopImages: ["/images/cases/SCHF-1.jpg"],
    postopImages: ["/images/cases/Slide1.jpeg"],
    authorIds: ["auth-8"],
    specialtyIds: ["spec-6"],
    publishedAt: "2020-09-05",
  },
  {
    id: "620aef053bcbb5003b7a4467",
    title: "Cubital Tunnel Release",
    slug: "cubital-tunnel-release",
    vimeoId: "453158136",
    thumbnailUrl: "/images/cases/Screen-Shot-2020-09-01-at-10.40.44-AM.png",
    preopImages: [],
    postopImages: [],
    authorIds: ["auth-2"],
    specialtyIds: ["spec-7"],
    publishedAt: "2020-09-01",
  },
  {
    id: "620aef053bcbb5003b7a4466",
    title: "Carpal Tunnel Release",
    slug: "esmail-carpal-tunnel",
    vimeoId: "453159089",
    thumbnailUrl: "/images/cases/Screen-Shot-2020-09-01-at-10.22.07-AM.png",
    preopImages: [],
    postopImages: [],
    authorIds: ["auth-2"],
    specialtyIds: ["spec-7"],
    publishedAt: "2020-09-01",
  },
  {
    id: "620aef053bcbb5003b7a4464",
    title: "Posterior Wall Acetabulum ORIF",
    slug: "posterior-wall-orif",
    vimeoId: "449539659",
    thumbnailUrl: "/images/cases/BeFunky-collage--7--3.jpg",
    preopImages: ["/images/cases/BeFunky-collage--6-.jpg"],
    postopImages: ["/images/cases/BeFunky-collage--7-.jpg"],
    authorIds: ["auth-6"],
    specialtyIds: ["spec-2"],
    publishedAt: "2020-07-24",
  },
  {
    id: "620aef053bcbb5003b7a4469",
    title: "Posterior Spinal Fusion for Scoliosis",
    slug: "untitlepd",
    vimeoId: "455121581",
    thumbnailUrl: "/images/cases/scoli-preop-1.jpg",
    preopImages: ["/images/cases/scoli-preop.jpg"],
    postopImages: ["/images/cases/scoli-postop.jpg"],
    authorIds: ["auth-3"],
    specialtyIds: ["spec-6", "spec-3"],
    publishedAt: "2020-07-15",
  },
  {
    id: "620aef053bcbb5003b7a4460",
    title: "Distal Femur ORIF",
    slug: "distal-femur-orif",
    vimeoId: "426881884",
    thumbnailUrl: "/images/cases/BeFunky-collage--5--1.jpg",
    preopImages: ["/images/cases/BeFunky-collage--5--2.jpg"],
    postopImages: ["/images/cases/BeFunky-collage--3-.jpg"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-2"],
    publishedAt: "2020-07-03",
  },
  {
    id: "620aef053bcbb5003b7a445f",
    title: "Ankle ORIF",
    slug: "ankle-orif",
    vimeoId: "410041933",
    thumbnailUrl: "/images/cases/Slide7--4-.jpg",
    preopImages: ["/images/cases/2020-08-Slide7--4-.jpg"],
    postopImages: ["/images/cases/Slide8--1-.jpg"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-2"],
    publishedAt: "2020-06-23",
  },
  {
    id: "620aef053bcbb5003b7a445d",
    title: "Monteggia Fracture ORIF",
    slug: "monteggia-fracture-orif",
    vimeoId: "426880240",
    thumbnailUrl: "/images/cases/Slide3--1--1.jpg",
    preopImages: ["/images/cases/BeFunky-collage--4--1.jpg"],
    postopImages: ["/images/cases/Slide12-1.jpg"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-1"],
    publishedAt: "2020-06-10",
  },
  {
    id: "620aef053bcbb5003b7a445e",
    title: "Distal Tibia IMN",
    slug: "distal-tibia-imn",
    vimeoId: "435248023",
    thumbnailUrl: "/images/cases/Screen-Shot-2020-07-11-at-5.05.36-PM.png",
    preopImages: ["/images/cases/2020-08-Screen-Shot-2020-07-11-at-5.05.36-PM.png"],
    postopImages: ["/images/cases/Screen-Shot-2020-07-11-at-5.05.57-PM.png"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-2"],
    publishedAt: "2020-05-26",
  },
  {
    id: "620aef053bcbb5003b7a4461",
    title: "Distal Humerus ORIF",
    slug: "distal-humerus-orif",
    vimeoId: "435540578",
    thumbnailUrl: "/images/cases/image-2-1.png",
    preopImages: ["/images/cases/image-2.png"],
    postopImages: ["/images/cases/image--2-.png"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-1"],
    publishedAt: "2020-05-21",
  },
  {
    id: "620aef053bcbb5003b7a4462",
    title: "Proximal Tibia IMN",
    slug: "proximal-tibia-imn",
    vimeoId: "399368326",
    thumbnailUrl: "/images/cases/image--3--1.png",
    preopImages: ["/images/cases/image--3-.png"],
    postopImages: ["/images/cases/image--1---1-.png"],
    authorIds: ["auth-1"],
    specialtyIds: ["spec-2"],
    publishedAt: "2020-05-14",
  },
];

// Helper functions
export function getAuthor(id: string): Author | undefined {
  return authors.find((a) => a.id === id);
}

export function getInstitution(id: string): Institution | undefined {
  return institutions.find((i) => i.id === id);
}

export function getSpecialties(ids: string[]): Specialty[] {
  return specialties.filter((s) => ids.includes(s.id));
}

export function getVideosByAuthor(authorId: string): Video[] {
  return videos.filter((v) => v.authorIds.includes(authorId));
}

export function getAuthors(ids: string[]): Author[] {
  return ids.map((id) => authors.find((a) => a.id === id)).filter(Boolean) as Author[];
}

export function getAuthorInstitution(author: Author): Institution | undefined {
  return getInstitution(author.institutionId);
}
